import { CatalogItem } from "./types";

export const catalog: CatalogItem[] = [
  {
    id: "mouse-001",
    name: "Mysz bezprzewodowa",
    nameEn: "Wireless Mouse",
    category: "Peryferia",
    categoryEn: "Peripherals",
    estimatedPrice: 150,
    description: "Ergonomiczna mysz bezprzewodowa z długim czasem pracy na baterii",
    descriptionEn: "Ergonomic wireless mouse with long battery life",
    icon: "🖱️",
  },
  {
    id: "keyboard-001",
    name: "Klawiatura mechaniczna",
    nameEn: "Mechanical Keyboard",
    category: "Peryferia",
    categoryEn: "Peripherals",
    estimatedPrice: 350,
    description: "Klawiatura mechaniczna z podświetleniem RGB",
    descriptionEn: "Mechanical keyboard with RGB backlight",
    icon: "⌨️",
  },
  {
    id: "monitor-001",
    name: "Monitor 24\" Full HD",
    nameEn: "Monitor 24\" Full HD",
    category: "Monitory",
    categoryEn: "Monitors",
    estimatedPrice: 900,
    description: "Monitor IPS 24 cale, Full HD, 75Hz, z regulacją wysokości",
    descriptionEn: "24-inch IPS monitor, Full HD, 75Hz, height adjustable",
    icon: "🖥️",
  },
  {
    id: "monitor-002",
    name: "Monitor 27\" QHD",
    nameEn: "Monitor 27\" QHD",
    category: "Monitory",
    categoryEn: "Monitors",
    estimatedPrice: 1500,
    description: "Monitor QHD 27 cali, 144Hz, dla profesjonalistów",
    descriptionEn: "27-inch QHD monitor, 144Hz, for professionals",
    icon: "🖥️",
  },
  {
    id: "headset-001",
    name: "Słuchawki z mikrofonem",
    nameEn: "Headset with Microphone",
    category: "Audio",
    categoryEn: "Audio",
    estimatedPrice: 280,
    description: "Słuchawki stereo z aktywną redukcją szumów i mikrofonem",
    descriptionEn: "Stereo headset with active noise cancellation and microphone",
    icon: "🎧",
  },
  {
    id: "webcam-001",
    name: "Kamera internetowa Full HD",
    nameEn: "Full HD Webcam",
    category: "Wideo",
    categoryEn: "Video",
    estimatedPrice: 250,
    description: "Kamera internetowa 1080p z wbudowanym mikrofonem",
    descriptionEn: "1080p webcam with built-in microphone",
    icon: "📷",
  },
  {
    id: "hub-001",
    name: "Hub USB-C 7-portowy",
    nameEn: "7-Port USB-C Hub",
    category: "Akcesoria",
    categoryEn: "Accessories",
    estimatedPrice: 180,
    description: "Hub USB-C z 7 portami: USB-A, USB-C, HDMI, SD card",
    descriptionEn: "USB-C hub with 7 ports: USB-A, USB-C, HDMI, SD card",
    icon: "🔌",
  },
  {
    id: "dock-001",
    name: "Stacja dokująca",
    nameEn: "Docking Station",
    category: "Akcesoria",
    categoryEn: "Accessories",
    estimatedPrice: 800,
    description: "Stacja dokująca z obsługą dwóch monitorów 4K",
    descriptionEn: "Docking station supporting dual 4K monitors",
    icon: "💻",
  },
  {
    id: "stand-001",
    name: "Podstawka pod laptop",
    nameEn: "Laptop Stand",
    category: "Akcesoria",
    categoryEn: "Accessories",
    estimatedPrice: 120,
    description: "Regulowana aluminiowa podstawka pod laptop",
    descriptionEn: "Adjustable aluminum laptop stand",
    icon: "📐",
  },
  {
    id: "chair-001",
    name: "Fotel ergonomiczny",
    nameEn: "Ergonomic Chair",
    category: "Meble",
    categoryEn: "Furniture",
    estimatedPrice: 1800,
    description: "Ergonomiczny fotel biurowy z regulacją lędźwi",
    descriptionEn: "Ergonomic office chair with lumbar adjustment",
    icon: "🪑",
  },
  {
    id: "lamp-001",
    name: "Lampa biurkowa LED",
    nameEn: "LED Desk Lamp",
    category: "Oświetlenie",
    categoryEn: "Lighting",
    estimatedPrice: 150,
    description: "Lampa biurkowa LED z regulacją jasności i temperatury barwowej",
    descriptionEn: "LED desk lamp with brightness and color temperature adjustment",
    icon: "💡",
  },
  {
    id: "mousepad-001",
    name: "Podkładka pod mysz XL",
    nameEn: "XL Mouse Pad",
    category: "Akcesoria",
    categoryEn: "Accessories",
    estimatedPrice: 60,
    description: "Duża podkładka pod mysz i klawiaturę, 900×400mm",
    descriptionEn: "Large mouse and keyboard pad, 900×400mm",
    icon: "🟦",
  },
];

export const getCatalogById = (id: string): CatalogItem | undefined =>
  catalog.find((item) => item.id === id);

export const categories = Array.from(new Set(catalog.map((i) => i.category)));
export const categoriesEn = Array.from(new Set(catalog.map((i) => i.categoryEn)));
